stages:
  - validate
  - build

default:
  before_script:
    - vagrant plugin install --local
  tags:
    - vagrant

validate:
  stage: validate
  script:
    - vagrant validate

build:
  stage: build
  script:
    # We build one at a time, since we have limited memory.
    - |
      while read -r name; do
        echo "Building ${name}"
        vagrant up "${name}"
        vagrant halt "${name}"
        # TODO: Register runner here
      done <<< $(vagrant status --machine-readable | awk 'BEGIN { FS = "," } ; { if ($3 == "state" && $4 == "not_created") { print $2 }}')
    - vagrant status
  only:
    - master

destroy:
  stage: build
  script:
    - |
      while read -r name; do
        echo "Destroying Vagrant ${name}"
        vagrant destroy --force "${name}"
      done <<< $(vagrant status --machine-readable | awk 'BEGIN { FS = "," } ; { if ($3 == "metadata") { print $2 }}')
    - |
      while read -r name; do
        echo "Destroying VM ${name}"
        vboxmanage unregistervm --delete "${name}"
      done <<< $(vboxmanage list vms | cut -d'"' -f2)
  when: manual
  only:
    - master
