stages:
  - validate
  - build
  - create

default:
  tags:
    - windows

validate:
  stage: validate
  script:
    - packer validate packer.pkr.hcl

build:
  stage: build
  script:
    - packer build -parallel-builds=1 --force packer.pkr.hcl
  only:
    - master

create:
  stage: create
  script:
    - vagrant down
    - vagrant up
    - vagrant halt
  only:
    - master
