stages:
  - validate
  - update
  - build
  - destroy

default:
  before_script:
    - vagrant plugin install --local
    # Ensure virtualbox has access to update the central configuration.
    - sudo /usr/bin/chmod g+rw -R /etc/vbox
  tags:
    - vagrant

.matrix_template: &matrix_definition
  matrix:
    # To update list, run:
    # vagrant status --machine-readable | awk 'BEGIN { FS = "," } ; { if ($3 == "metadata") { print "  - " $2 }}'
    - name: ubuntu1804distro
    - name: ubuntu1804upstream
    - name: ubuntu2004distro
    - name: ubuntu2004upstream
    - name: rhel7distro
    - name: rhel7upstream
    - name: rhel8distro
    - name: rhel8upstream
    - name: centos7distro
    - name: centos7upstream
    - name: centos8distro
    - name: centos8upstream
    - name: archdistro
    - name: windows_server
    - name: windows_10

validate:
  stage: validate
  script:
    - vagrant validate

update:
  stage: update
  script:
    - vagrant box update

build:
  stage: build
  script:
    # We build one at a time, since we have limited memory.
    - vagrant up "${name}"
    - export SSH_USER=$(vagrant ssh-config "${name}" | awk '{ if ($1 == "User") { print $2 }}')
    - export SSH_IDENTITY_FILE=$(vagrant ssh-config "${name}" | awk '{ if ($1 == "IdentityFile") { print $2 }}')
    - sudo gitlab-runner unregister --name "${name}" || true
    - sudo --preserve-env=CI_SERVER_URL,REGISTRATION_TOKEN,SSH_USER,SSH_IDENTITY_FILE gitlab-runner register --non-interactive --name "${name}" --executor virtualbox --virtualbox-base-name "${name}" --tag-list "cross-distros-testers,${name}" --ssh-user="${SSH_USER}" --ssh-identity-file="${SSH_IDENTITY_FILE}"
    - vagrant halt "${name}"
  parallel:
    <<: *matrix_definition
  when: manual
  only:
    - master

destroy:
  stage: destroy
  script:
    - vagrant destroy --force "${name}"
  parallel:
    <<: *matrix_definition
  when: manual
  only:
    - master

destroyall:
  stage: destroy
  script:
    - |
      while read -r name; do
        echo "Destroying Vagrant ${name}"
        vagrant destroy --force "${name}"
      done <<< $(vagrant status --machine-readable | awk 'BEGIN { FS = "," } ; { if ($3 == "metadata") { print $2 }}')
    - sleep 30
    # Clean up any VMs that Vagrant lost
    - |
      while read -r name; do
        echo "Destroying VM ${name}"
        vboxmanage unregistervm --delete "${name}" || true
      done <<< $(vboxmanage list vms | cut -d'"' -f2)
    # Clean up an VMs that VirtualBox lost
    - killall -9 VBoxHeadless || true
    # Deleting any remaining VM state
    - rm -rf ~/Virtualbox\ VMs/*
  when: manual
  only:
    - master
