---
- name: RHEL register
  hosts: distro_rhel
  become: true
  tasks:
  - name: Register and auto-subscribe to available content.
    redhat_subscription:
      state: present
      username: "{{ redhat_username | mandatory }}"
      password: "{{ redhat_password | mandatory }}"
      auto_attach: true
- name: RHEL setup
  hosts: release_rhel7
  become: true
  tasks:
  - name: Enable Red Hat Extras Repository
    rhsm_repository:
      name:
        - rhel-7-server-extras-rpms
      state: enabled
- name: RHEL/CentOS packages
  hosts: distro_rhel:distro_centos
  become: true
  tasks:
  - name: Upgrade all packages
    yum:
      name: '*'
      state: latest
      update_cache: yes
      lock_timeout: 1
- name: Ubuntu packages
  hosts: distro_ubuntu
  become: true
  tasks:
  - name: Upgrade all packages
    apt:
      name: '*'
      state: latest
- name: Arch packages
  hosts: distro_arch
  become: true
  tasks:
  - name: Upgrade all packages
    pacman:
      update_cache: yes
      upgrade: yes
- name: Base packages
  hosts: all
  become: true
  tasks:
  - name: Install a list of basic packages
    package:
      name:
        - bash
        - zsh
        - mksh
        - git

- name: Non-Ubuntu distro Docker
  hosts: docker_distro:!distro_ubuntu
  become: true
  tasks:
  - name: Install distro docker
    package:
      name: docker
- name: Ubuntu distro Docker
  hosts: docker_distro:&distro_ubuntu
  become: true
  tasks:
  - name: Install distro docker
    apt:
      name: docker.io
- name: Upstream Docker
  hosts: docker_upstream
  become: true
  vars:
    docker_install_compose: false
  roles:
    - geerlingguy.docker
- name: Docker setup
  hosts: all
  become: true
  tasks:
  - name: Ensure group "docker" exists
    group:
      name: docker
  - name: Ensure vagrant user are added to the docker group
    user:
      name: vagrant
      groups: docker
      append: true
  - name: Ensure Docker is started and enabled at boot
    service:
      name: docker
      state: started
      enabled: true

- name: Install Gitlab Runner (binary only, distro)
  hosts: all:!family_el8:!distro_arch
  roles:
    - role: lean_delivery.gitlab_runner
  vars:
    gitlab_runner_concurrent: 1
    gitlab_runner_skip_registration: true
- name: RHEL/CentOS 8 Install Gitlab Runner (binary only)
  hosts: family_el8:!distro_arch
  roles:
    - role: lean_delivery.gitlab_runner
  vars:
    gitlab_runner_concurrent: 1
    gitlab_runner_skip_registration: true
    yum_libselinux_python_library: python3-libselinux
    yum_libselinux_config_libraries: [python3-policycoreutils, python3-libsemanage]
    python_executable: python3
    pip_executable: /usr/bin/pip3
- name: Arch Install Gitlab Runner (binary only)
  hosts: distro_arch
  become: true
  tasks:
  - name: Install a list of basic packages
    package:
      name: gitlab-runner
